name: DFChatImprovements
version: '2.0.3'
main: uk.co.nikodem.dFChatImprovements.DFChatImprovements
api-version: '1.20'
softdepend: [UltimateAdvancementAPI]
commands:
  flex:
    aliases: ["showitem", "flexitem", "itemshow", "chatitem"]
    description: "Put your item into the chat for everyone to see"